image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: capgemini
  APP_NAME: graphy
  REPO: graphy

stages:
  - build
  - deploy 

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean package -DskipTests" 
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: deploy 
  script:
    - docker login -u magnarox -p $CI_BUILD_TOKEN registry.hub.docker.com
    - docker build -t registry.hub.docker.com/magnarox/$REPO . 
    - docker push registry.hub.docker.com/magnarox/$REPO 


