image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  CI_DOCKER_REGISTRY: registry.hub.docker.com
  CI_DOCKER_IMAGE: magnarox/graphy
  CI_DOCKER_BUILD_NUMBER: 1.0.0
  APP_NAME: graphy
  CONTAINER_IMAGE: $CI_DOCKER_REGISTRY/$CI_DOCKER_IMAGE:$CI_DOCKER_BUILD_NUMBER
  KUBECTL_VERSION: v1.13.3

stages:
  - build-jar
  - build-docker
  - deploy 

maven-build:
  image: maven:3-jdk-8
  stage: build-jar
  script: "mvn clean package -DskipTests" 
  artifacts:
    paths:
      - target/*.jar
      - target/*.sh
      - target/Dockerfile

docker-build:
  stage: build-docker 
  script:
    - docker login -u $CI_BUILD_USER -p $CI_BUILD_TOKEN $CI_DOCKER_REGISTRY
    - cd target
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE 
	
deploy_dev:
  stage: deploy
  image: alpine
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl config set-cluster nosebit --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --username="$KUBE_USER" --password="$KUBE_PASSWORD"
    - kubectl config set-context default --cluster=nosebit --user=admin
    - kubectl config use-context default
    - kubectl apply -f src/main/kubernetes/graphy-deployment.yml

