version: '3'
services:
  graphy:
    image: graphy
    environment:
      JAVA_OPTS: -Xms256m -Xmx2048m
      ENDPOINT: janusgraph
      PORT: 8182
      VERTEX_THRESHOLD: 4
    networks:
    - graph
networks:
  graph:
    external: true