version: '3'
services:
  graphy:
    image: graphy
    environment:
      JAVA_OPTS: -Xms128m -Xmx512m
      ENDPOINT: janusgraph
      PORT: 8182
      VERTEX_THRESHOLD: 10
    networks:
    - graph
networks:
  graph:
    external: true