version: '3'
services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 30s
      retries: 30
    ports:
    - "9200:9200"
    volumes:
    - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
    - graph

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    #command: /bin /bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    #environment :
    # - "HEAP_NEWSIZE:4096M"
    # - "MAX_HEAP_SIZE:4096M"
    environment:
          JAVA_OPTS: -Xms256m -Xmx4048m
    expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
    volumes: # uncomment if you desire mounts, also uncomment cluster.sh
    #  - C:\dev\insight\src\main\docker\compose\graph\cassandra:/var/lib/cassandra
    #- named_vol:/var/lib/cassandra
    - ./janus/conf/cassandra.yaml:/etc/cassandra/cassandra.yaml
    #  - C:\dev\insight\src\main\docker\compose\graph\janus\conf\jvm.options:/etc/cassandra/jvm.options
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
    networks:
    - graph
#volumes:
#  named_vol:
networks:
  graph:
    external: true