version: '3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    #command: /bin /bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    #environment :
    # - "HEAP_NEWSIZE:4096M"
    # - "MAX_HEAP_SIZE:4096M"
    environment:
          JAVA_OPTS: -Xms256m -Xmx2048m
    expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160
    volumes:
    #- ./cassandra/data:/var/lib/cassandra
    - ./cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
    # Cassandra ulimt recommended settings
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
    networks:
    - insight
networks:
  insight:
    external: true
