version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    volumes:
    - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
    - "5601:5601"
    networks:
    - insight
    environment:
    - "ELASTICSEARCH_URL=http://elasticsearch:9200"
networks:
  insight:
    external: true