version: '3'
services:
#    insight-kibana:
#        image: docker.elastic.co/kibana/kibana:6.6.0
#        container_name: kibana
#        ports:
#            - "5601:5601"
#        volumes:
#            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
#        networks:
#            - insight
    insight-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./es/data:/usr/share/elasticsearch/data
        networks:
            - insight
networks:
    insight:
        external: true


