version: '3'
services:
    #kibana:
     #   image: docker.elastic.co/kibana/kibana-oss:6.4.2
     #   container_name: kibana
     #   ports:
     #       - "5601:5601"
     #   environment:
     #       - "ELASTICSEARCH_URL=http://elasticsearch:9200"
     #   networks:
     #       - insight
    insight-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./es/data:/usr/share/elasticsearch/data
        networks:
            - insight
networks:
    insight:
        external: true


